### ISSUE TITLE
Auto conversion of UM output files to NetCDF

### ISSUE THREAD

**Issue by kieranricardo** [ACCESS-NRI/esm-historical#1]

**Comment by kieranricardo** [comment]
@MartinDix I did several test runs, several months as seperate runs, and one two year run and all the files were converted. Eyeballing the converting files (using `xarray` and `xconv`) the files look correct but I haven't formally tested them. I'm planning on checking for identical values in a subset of the files - any recommendations for libraries to load in the UM output data?

**Comment by kieranricardo** [comment]
And should this delete the original UM output once its been converted?

**Comment by MartinDix** [comment]
Best way to read the data is iris https://scitools-iris.readthedocs.io/en/stable/

This is part of the COE hh5 conda/analysis3 environment.

It's a bit circular because that's what's used in the netCDF conversion.

Probably best to have an option to delete the UM format files.

**Comment by kieranricardo** [comment]
the `netcdf` conversion is rounding from `f64` to `f32` but other than the that the outputs are identical. @MartinDix should this rounding be happening?

**Comment by aidanheerdegen** [comment]
I'd like to archive this repo @kieranricardo. Is this issue still relevant given we have https://github.com/ACCESS-NRI/um2nc-standalone

If so, can we transfer it there?

**Comment by kieranricardo** [comment]
@aidanheerdegen I actually forgot this (extremely) stale issue even existed! I'll close this one
